// <auto-generated />
using System;
using InventarisApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarisApp.Migrations
{
    [DbContext(typeof(InventarisContext))]
    [Migration("20260423085217_AddLokalenFunctionality")]
    partial class AddLokalenFunctionality
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InventarisApp.Models.Device", b =>
                {
                    b.Property<int>("device_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("device_id"));

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("device_id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("InventarisApp.Models.Info", b =>
                {
                    b.Property<string>("type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("device_id")
                        .HasColumnType("int");

                    b.Property<int?>("LokaalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("aankoopdatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("apparaatnaam")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("eind_garantie")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("eind garantie");

                    b.Property<int?>("garantie")
                        .HasColumnType("int");

                    b.Property<string>("ip")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("leverancier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("merk")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("serial_number")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial number");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("type", "device_id");

                    b.HasIndex("LokaalId");

                    b.HasIndex("device_id");

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("InventarisApp.Models.Lening", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("einddatum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("persoonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("startdatum")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("DeviceId");

                    b.HasIndex("persoonID");

                    b.ToTable("Leningen");
                });

            modelBuilder.Entity("InventarisApp.Models.Lokaal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Lokalen");
                });

            modelBuilder.Entity("InventarisApp.Models.Materiaal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("LokaalId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("LokaalId");

                    b.ToTable("Materialen");
                });

            modelBuilder.Entity("InventarisApp.Models.Persoon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("emailadres")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("functie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("InventarisApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasswordHash = "$2a$11$eNfFxyOQ/7o76hXwE/18/.M9v2vDkY6m8tP51BwEZyV44Qx74o77G",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("InventarisApp.Models.Wifi", b =>
                {
                    b.Property<int>("wifi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("wifi_id"));

                    b.Property<int>("device_id")
                        .HasColumnType("int");

                    b.Property<string>("local_ip")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("mac_address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("wifi_id");

                    b.HasIndex("type", "device_id");

                    b.ToTable("Wifis");
                });

            modelBuilder.Entity("InventarisApp.Models.Info", b =>
                {
                    b.HasOne("InventarisApp.Models.Lokaal", "Lokaal")
                        .WithMany("Devices")
                        .HasForeignKey("LokaalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InventarisApp.Models.Device", "Device")
                        .WithMany("Infos")
                        .HasForeignKey("device_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Lokaal");
                });

            modelBuilder.Entity("InventarisApp.Models.Lening", b =>
                {
                    b.HasOne("InventarisApp.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarisApp.Models.Persoon", "Persoon")
                        .WithMany("Leningen")
                        .HasForeignKey("persoonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Persoon");
                });

            modelBuilder.Entity("InventarisApp.Models.Materiaal", b =>
                {
                    b.HasOne("InventarisApp.Models.Lokaal", "Lokaal")
                        .WithMany("Materialen")
                        .HasForeignKey("LokaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokaal");
                });

            modelBuilder.Entity("InventarisApp.Models.Wifi", b =>
                {
                    b.HasOne("InventarisApp.Models.Info", "Info")
                        .WithMany("Wifis")
                        .HasForeignKey("type", "device_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Info");
                });

            modelBuilder.Entity("InventarisApp.Models.Device", b =>
                {
                    b.Navigation("Infos");
                });

            modelBuilder.Entity("InventarisApp.Models.Info", b =>
                {
                    b.Navigation("Wifis");
                });

            modelBuilder.Entity("InventarisApp.Models.Lokaal", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Materialen");
                });

            modelBuilder.Entity("InventarisApp.Models.Persoon", b =>
                {
                    b.Navigation("Leningen");
                });
#pragma warning restore 612, 618
        }
    }
}
