// <auto-generated />
using System;
using InventarisApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarisApp.Migrations
{
    [DbContext(typeof(InventarisContext))]
    [Migration("20260313112223_OpslagPerCampus")]
    partial class OpslagPerCampus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InventarisApp.Models.Device", b =>
                {
                    b.Property<int>("device_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("device_id"));

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("device_id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("InventarisApp.Models.Info", b =>
                {
                    b.Property<string>("type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("device_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("aankoopdatum")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("eind_garantie")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("eind garantie");

                    b.Property<int?>("garantie")
                        .HasColumnType("int");

                    b.Property<string>("ip")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("leverancier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("locatie_id")
                        .HasColumnType("int");

                    b.Property<string>("lokaalnr")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("merk")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("serial_number")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial number");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("type", "device_id");

                    b.HasIndex("device_id");

                    b.HasIndex("locatie_id", "lokaalnr");

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("InventarisApp.Models.Locatie", b =>
                {
                    b.Property<int>("locatie_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("locatie_id"));

                    b.Property<string>("abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("locatie_id");

                    b.ToTable("Locaties");

                    b.HasData(
                        new
                        {
                            locatie_id = 1,
                            abbreviation = "CR",
                            naam = "Campus Rouppe"
                        },
                        new
                        {
                            locatie_id = 2,
                            abbreviation = "CL",
                            naam = "Campus Landsroem"
                        });
                });

            modelBuilder.Entity("InventarisApp.Models.Lokaal", b =>
                {
                    b.Property<int>("locatie_id")
                        .HasColumnType("int");

                    b.Property<string>("lokaalnr")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("plaatsen")
                        .HasColumnType("int");

                    b.HasKey("locatie_id", "lokaalnr");

                    b.ToTable("Lokalen");

                    b.HasData(
                        new
                        {
                            locatie_id = 1,
                            lokaalnr = "Opslag",
                            plaatsen = 0
                        },
                        new
                        {
                            locatie_id = 2,
                            lokaalnr = "Opslag",
                            plaatsen = 0
                        });
                });

            modelBuilder.Entity("InventarisApp.Models.Wifi", b =>
                {
                    b.Property<int>("wifi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("wifi_id"));

                    b.Property<int>("device_id")
                        .HasColumnType("int");

                    b.Property<string>("local_ip")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("mac_address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("wifi_id");

                    b.HasIndex("type", "device_id");

                    b.ToTable("Wifis");
                });

            modelBuilder.Entity("InventarisApp.Models.Info", b =>
                {
                    b.HasOne("InventarisApp.Models.Device", "Device")
                        .WithMany("Infos")
                        .HasForeignKey("device_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarisApp.Models.Lokaal", "Lokaal")
                        .WithMany("Infos")
                        .HasForeignKey("locatie_id", "lokaalnr")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("Lokaal");
                });

            modelBuilder.Entity("InventarisApp.Models.Lokaal", b =>
                {
                    b.HasOne("InventarisApp.Models.Locatie", "Locatie")
                        .WithMany("Lokalen")
                        .HasForeignKey("locatie_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("InventarisApp.Models.Wifi", b =>
                {
                    b.HasOne("InventarisApp.Models.Info", "Info")
                        .WithMany("Wifis")
                        .HasForeignKey("type", "device_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Info");
                });

            modelBuilder.Entity("InventarisApp.Models.Device", b =>
                {
                    b.Navigation("Infos");
                });

            modelBuilder.Entity("InventarisApp.Models.Info", b =>
                {
                    b.Navigation("Wifis");
                });

            modelBuilder.Entity("InventarisApp.Models.Locatie", b =>
                {
                    b.Navigation("Lokalen");
                });

            modelBuilder.Entity("InventarisApp.Models.Lokaal", b =>
                {
                    b.Navigation("Infos");
                });
#pragma warning restore 612, 618
        }
    }
}
